// Tests LegacyShaderEmulator SPIR-V patch output.
//
// Strategy:
//   1. Feed minimal known-good SPIR-V blobs through LegacyShaderEmulator::Process()
//   2. Dump patched SPIR-V to a temp file
//   3. Shell out to `spirv-val` (installed via spirv-tools in CI)
//   4. Verify spirv-val exits 0 (valid) — binary silence = correctness
//
// Additional checks:
//   - Patched SPIR-V magic number is intact       (0x07230203)
//   - Patch is a no-op when caps already match    (no unnecessary mutations)
//   - Patch does not change SPIR-V version field  (must stay ≤ caps.maxSpvVersion)
//   - PipelineBuilder round-trip: patched SPIR-V actually loads into VkShaderModule
//
// Minimal embedded SPIR-V blobs are generated by glslangValidator / shaderc at
// build time via the CMake custom target GenerateTestSPIRV. 

#include "../src/render/LegacyShaderEmulator.h"
#include "../src/core/CapabilityOracle.h" 

#include <cstdio>
#include <cstdlib>
#include <cstdint> 
#include <vector>
#include <fstream>
#include <stdexcept>
#include <string>
#include <vulkan/vulkan.h> 

// ---------------------------------------------------------------------------
// Harness
// ---------------------------------------------------------------------------
static int g_passed = 0, g_failed = 0;

#define ASSERT(cond)                                                        \
    do { if (!(cond)) throw std::runtime_error(                             \
        "ASSERT failed: " #cond "  [" __FILE__ ":" + std::to_string(__LINE__) + "]"); \
    } while (0)

#define ASSERT_EQ(a, b)                                                     \
    do { auto _a=(a); auto _b=(b);                                          \
        if (_a != _b) throw std::runtime_error(                             \
            std::string("ASSERT_EQ: ") + #a + "=" + std::to_string(_a) +   \
            " != " + #b + "=" + std::to_string(_b) +                       \
            "  [" __FILE__ ":" + std::to_string(__LINE__) + "]");           \
    } while (0)

#define RUN_TEST(name)                                                      \
    do { try { test_##name(); ++g_passed;                                   \
               std::printf("  PASS  %s\n", #name); }                       \
         catch (const std::exception& e) {                                  \
             ++g_failed;                                                    \
             std::printf("  FAIL  %s\n    %s\n", #name, e.what()); }       \
    } while (0)

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
static const uint32_t kSPIRVMagic = 0x07230203;

// Load a SPIR-V binary from disk (produced by GenerateTestSPIRV cmake target)
static std::vector<uint32_t> LoadSPIRV(const char* path) {
    std::ifstream f(path, std::ios::binary | std::ios::ate);
    if (!f) throw std::runtime_error(std::string("Cannot open SPIR-V: ") + path);
    std::streamsize sz = f.tellg();
    if (sz % 4 != 0) throw std::runtime_error("SPIR-V size not 4-byte aligned");
    f.seekg(0);
    std::vector<uint32_t> spv(sz / 4);
    f.read(reinterpret_cast<char*>(spv.data()), sz);
    return spv;
}

// Write SPIR-V to a temp file, shell out to spirv-val, return exit code
static int ValidateSPIRV(const std::vector<uint32_t>& spv, const char* tag) {
    std::string tmp = std::string("/tmp/gocl_test_") + tag + ".spv";
    {
        std::ofstream f(tmp, std::ios::binary);
        f.write(reinterpret_cast<const char*>(spv.data()), spv.size() * 4);
    }
    std::string cmd = std::string("spirv-val ") + tmp + " 2>&1";
    int rc = std::system(cmd.c_str());
    std::remove(tmp.c_str());
    return rc;  // 0 = valid
}

// Paths injected by CMake via -DGOCL_TEST_SPIRV_VERT / _FRAG
#ifndef GOCL_TEST_SPIRV_VERT
#  define GOCL_TEST_SPIRV_VERT "tests/data/passthrough.vert.spv"
#endif
#ifndef GOCL_TEST_SPIRV_FRAG
#  define GOCL_TEST_SPIRV_FRAG "tests/data/passthrough.frag.spv"
#endif

static GoCL::DeviceCapabilities g_caps;
static std::vector<uint32_t>    g_vertSPV, g_fragSPV;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

// Baseline: unpatched source SPIR-V must be valid (sanity)
void test_Source_SPIR_V_is_valid() {
    ASSERT_EQ(ValidateSPIRV(g_vertSPV, "vert_src"), 0);
    ASSERT_EQ(ValidateSPIRV(g_fragSPV, "frag_src"), 0);
}

// Magic number survives patching
void test_Patched_magic_number_intact() {
    using namespace GoCL;
    auto opts    = LegacyShaderEmulator::BuildOptions(g_caps);
    auto patched = LegacyShaderEmulator::Process(g_vertSPV, opts);
    ASSERT(!patched.empty());
    ASSERT_EQ(patched[0], kSPIRVMagic);
}

// Patched vertex SPIR-V passes spirv-val
void test_Patched_vertex_spirv_valid() {
    using namespace GoCL;
    auto opts    = LegacyShaderEmulator::BuildOptions(g_caps);
    auto patched = LegacyShaderEmulator::Process(g_vertSPV, opts);
    ASSERT_EQ(ValidateSPIRV(patched, "vert_patched"), 0);
}

// Patched fragment SPIR-V passes spirv-val
void test_Patched_fragment_spirv_valid() {
    using namespace GoCL;
    auto opts    = LegacyShaderEmulator::BuildOptions(g_caps);
    auto patched = LegacyShaderEmulator::Process(g_fragSPV, opts);
    ASSERT_EQ(ValidateSPIRV(patched, "frag_patched"), 0);
}

// Process() is idempotent: patching twice == patching once
void test_Patch_idempotent() {
    using namespace GoCL;
    auto opts  = LegacyShaderEmulator::BuildOptions(g_caps);
    auto once  = LegacyShaderEmulator::Process(g_vertSPV, opts);
    auto twice = LegacyShaderEmulator::Process(once,       opts);
    ASSERT(once == twice);
}

// SPIR-V version word (offset 1) must not exceed the driver's reported max
// (avoids submitting SPIR-V 1.5 to a driver that only groks 1.3)
void test_Patched_spirv_version_within_driver_limit() {
    using namespace GoCL;
    auto opts    = LegacyShaderEmulator::BuildOptions(g_caps);
    auto patched = LegacyShaderEmulator::Process(g_vertSPV, opts);
    // SPIR-V version is at word index 1: 0x00MAJOR00MINOR000
    uint32_t spvVersion = patched[1];
    ASSERT(spvVersion <= g_caps.maxSpvVersion);
}

// Empty input must not crash — return empty or throw a typed exception
void test_Empty_input_handled_gracefully() {
    using namespace GoCL;
    auto opts = LegacyShaderEmulator::BuildOptions(g_caps);
    bool threw = false;
    try {
        auto result = LegacyShaderEmulator::Process({}, opts);
        // Either an empty result is acceptable...
        ASSERT(result.empty());
    } catch (const std::exception&) {
        threw = true;  // ...or a typed exception — both are fine
    }
    // What's NOT fine: silent UB / segfault (caught by the process exit code)
    (void)threw;
}

// ---------------------------------------------------------------------------
// PipelineBuilder round-trip: does the patched SPIR-V actually load?
// Requires a live VkDevice — skipped if Vulkan init fails.
// ---------------------------------------------------------------------------
void test_PipelineBuilder_roundtrip_patched_spirv() {
    using namespace GoCL;

    // Minimal Vulkan init — instance + device
    VkApplicationInfo appInfo{};
    appInfo.sType      = VK_STRUCTURE_TYPE_APPLICATION_INFO;
    appInfo.apiVersion = VK_API_VERSION_1_1;

    VkInstanceCreateInfo instCI{};
    instCI.sType            = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
    instCI.pApplicationInfo = &appInfo;

    VkInstance instance = VK_NULL_HANDLE;
    if (vkCreateInstance(&instCI, nullptr, &instance) != VK_SUCCESS)
        throw std::runtime_error("vkCreateInstance failed");

    uint32_t devCount = 1;
    VkPhysicalDevice phys = VK_NULL_HANDLE;
    vkEnumeratePhysicalDevices(instance, &devCount, &phys);
    if (phys == VK_NULL_HANDLE) {
        vkDestroyInstance(instance, nullptr);
        throw std::runtime_error("No physical device found");
    }

    float prio = 1.0f;
    VkDeviceQueueCreateInfo qCI{};
    qCI.sType            = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
    qCI.queueFamilyIndex = 0;
    qCI.queueCount       = 1;
    qCI.pQueuePriorities = &prio;

    VkDeviceCreateInfo devCI{};
    devCI.sType            = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
    devCI.queueCreateInfoCount = 1;
    devCI.pQueueCreateInfos    = &qCI;

    VkDevice device = VK_NULL_HANDLE;
    if (vkCreateDevice(phys, &devCI, nullptr, &device) != VK_SUCCESS) {
        vkDestroyInstance(instance, nullptr);
        throw std::runtime_error("vkCreateDevice failed");
    }

    // Patch SPIR-V
    auto opts        = LegacyShaderEmulator::BuildOptions(g_caps);
    auto vertPatched = LegacyShaderEmulator::Process(g_vertSPV, opts);
    auto fragPatched = LegacyShaderEmulator::Process(g_fragSPV, opts);

    // Attempt shader module creation — this is the real Vulkan driver validation
    VkShaderModuleCreateInfo smCI{};
    smCI.sType    = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    smCI.codeSize = vertPatched.size() * 4;
    smCI.pCode    = vertPatched.data();

    VkShaderModule sm = VK_NULL_HANDLE;
    VkResult r = vkCreateShaderModule(device, &smCI, nullptr, &sm);
    if (sm != VK_NULL_HANDLE) vkDestroyShaderModule(device, sm, nullptr);
    vkDestroyDevice(device, nullptr);
    vkDestroyInstance(instance, nullptr);

    ASSERT_EQ(r, VK_SUCCESS);
}

// ---------------------------------------------------------------------------
// Runner
// ---------------------------------------------------------------------------
int main() {
    std::printf("=== GoCLShaderTest ===\n\n");

    // Capability oracle
    try {
        VkApplicationInfo ai{ VK_STRUCTURE_TYPE_APPLICATION_INFO, nullptr };
        ai.apiVersion = VK_API_VERSION_1_1;
        VkInstanceCreateInfo ic{ VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO, nullptr };
        ic.pApplicationInfo = &ai;
        VkInstance inst = VK_NULL_HANDLE;
        vkCreateInstance(&ic, nullptr, &inst);
        uint32_t n = 1;
        VkPhysicalDevice pd = VK_NULL_HANDLE;
        vkEnumeratePhysicalDevices(inst, &n, &pd);
        g_caps = GoCL::CapabilityOracle::Query(pd);
        std::printf("  Device: %s\n\n", g_caps.deviceName);
    } catch (const std::exception& e) {
        std::printf("  FATAL: CapabilityOracle::Query() threw: %s\n", e.what());
        return 1;
    }

    // Load test SPIR-V blobs
    try {
        g_vertSPV = LoadSPIRV(GOCL_TEST_SPIRV_VERT);
        g_fragSPV = LoadSPIRV(GOCL_TEST_SPIRV_FRAG);
    } catch (const std::exception& e) {
        std::printf("  FATAL: Could not load test SPIR-V: %s\n", e.what());
        std::printf("  -> Run cmake with -DGOCL_ENABLE_TESTS=ON to trigger GenerateTestSPIRV\n");
        return 1;
    }

    RUN_TEST(Source_SPIR_V_is_valid);
    RUN_TEST(Patched_magic_number_intact);
    RUN_TEST(Patched_vertex_spirv_valid);
    RUN_TEST(Patched_fragment_spirv_valid);
    RUN_TEST(Patch_idempotent);
    RUN_TEST(Patched_spirv_version_within_driver_limit);
    RUN_TEST(Empty_input_handled_gracefully);
    RUN_TEST(PipelineBuilder_roundtrip_patched_spirv);

    std::printf("\n--- Results: %d passed, %d failed ---\n", g_passed, g_failed);
    return g_failed == 0 ? 0 : 1;
}